# Generated by Django 4.1.7 on 2023-03-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABLine',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('heading', models.FloatField()),
                ('aPoint_lat', models.FloatField()),
                ('aPoint_lon', models.FloatField()),
                ('bPoint_lat', models.FloatField()),
                ('bPoint_lon', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('lastModifiedTime', models.DateTimeField()),
                ('archived', models.BooleanField()),
            ],
        ),
    ]
